# Array Opration

In [2]:
!pip install numpy

In [3]:
import numpy as np

In [5]:
a1 = np.arange(12).reshape(3,4)
print(a1)
print(a1**2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [7]:
a2 = np.arange(12,24).reshape(3,4)
print(a2)
print(a1)
print(a2 == 15)
print(a2 > 5)
print(a2 < a1)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False  True]
 [False False False False]
 [False False False False]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[[False False False False]
 [False False False False]
 [False False False False]]


# Array Function 

In [11]:
a1 = np.random.random((3,3))
print(a1)

[[0.2793827  0.25423035 0.50079331]
 [0.68206976 0.82741462 0.56443454]
 [0.0706527  0.79318819 0.40496912]]


In [9]:
np.random.seed(1)
a1 =np.round( np.random.random((3,3)) * 100)
print(a1)

[[42. 72.  0.]
 [30. 15.  9.]
 [19. 35. 40.]]


In [10]:
print(np.sum(a1,axis=0))

[ 91. 122.  49.]


In [20]:
print(np.round(np.mean(a1,axis=1),1)) # average of each row in a1, rounds those averages to 1 decimal place,

[38.  18.  31.3]


In [21]:
vals = np.array([1,2,3,4,7,8])
print(vals)

[1 2 3 4 7 8]


In [22]:
print(np.round(np.log(vals),2)) #the natural logarithm (logₑ) of every value in vals and
# 2 means round 2 decimal place

[0.   0.69 1.1  1.39 1.95 2.08]


In [23]:
print(np.round(np.sin(vals),2)) # calculates the sine of each value in vals, rounds each answer to 2 decimal places, and prints it.

[ 0.84  0.91  0.14 -0.76  0.66  0.99]


In [24]:
print(np.floor(vals)) # np.floor(vals) rounds every value in vals downward to the nearest whole number.
print(np.ceil(vals))  # np.ceil(vals) means: round every value in vals upward to the nearest whole number.

[1 2 3 4 7 8]
[1 2 3 4 7 8]


In [26]:
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)
print(a2)
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [27]:
print(np.dot(a2,a3))

[[114 120 126]
 [378 400 422]
 [642 680 718]]


# Indexing and slicing 

In [28]:
a1 = np.arange(12)
print(a1)
a2 = np.arange(12).reshape(3,4)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
print(a1[0],a1[-1],a1[5])

0 11 5


In [31]:
print(a2[1,0],a2[2,3])

4 11


In [33]:
a3 = np.arange(12).reshape(2,2,3)
print(a3)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [35]:
print(a3[1,0,1],a3[1,1,0,])

7 9


In [36]:
print(a1)
print(a2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [38]:
print(a1[2:8:2]) # start , stop , step

[2 4 6]


In [40]:
print(a1[::-1])

[11 10  9  8  7  6  5  4  3  2  1  0]


In [41]:
print(a2[0:2,1::2])

[[1 3]
 [5 7]]


# Iteriting :

In [44]:
a1 = np.arange(12)
print(a1)
for i in a1:
    print(i,end='')

[ 0  1  2  3  4  5  6  7  8  9 10 11]
01234567891011

In [47]:
a2 = np.arange(12).reshape(3,4)
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [48]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [51]:
print(a3)
for value in np.nditer(a3):
    print(value)

    # np.nditer lets you loop through every element of a NumPy array one by one,
    # regardless of whether the array is 1D, 2D, or 3D.


[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
0
1
2
3
4
5
6
7


# Reshaping

In [52]:
a = np.arange(1,7)
print(a)

[1 2 3 4 5 6]


In [53]:
n = a.reshape(2,3)
print(n)

[[1 2 3]
 [4 5 6]]


In [54]:
a3 = np.arange(8).reshape(2,2,2)
print(a3)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [56]:
print(a3.ravel())
 # .ravel() converts a multi-dimensional NumPy array into a single 1D array. 

[0 1 2 3 4 5 6 7]


In [67]:
b = np.arange(12) 
print(b)
print(b.reshape(3,-1))  # -1 automatically decide the column 

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [68]:
b = np.arange(8)   # -1 automatically decide the column 
print(b)
print(b.reshape(2,-1))

[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]


In [69]:
b = np.arange(12)  # -1 automatically decide the column  
print(b)
print(b.reshape(2,-1))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [72]:
m =np.array([[1,2],[3,4]])
print(m)
r = m.ravel()
print(r)

[[1 2]
 [3 4]]
[1 2 3 4]


In [73]:
r[0] = 99
print(m)
print(r)

[[99  2]
 [ 3  4]]
[99  2  3  4]


In [74]:
s = m.flatten()  # .flatten() means: make an array flat—convert 2D or 3D data into one single row.
print(s)

[99  2  3  4]


### ravel() usually returns a view of the original array. Changing it can change the original array.
### flatten() always returns a copy. Changing it does not change the original array.

In [75]:
s = m.flatten()
print(s)

[99  2  3  4]


In [76]:
s[2]=555
print(m)
print(s)

[[99  2]
 [ 3  4]]
[ 99   2 555   4]


# Stacking

In [78]:
a4 = np.arange(12).reshape(3,4)
print(a4)
a5 = np.arange(12,24).reshape(3,4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [80]:
print(np.hstack((a4,a5))) # .hstack() joins arrays horizontally
print(np.vstack((a4,a5))) # .vstack() joins arrays vertically

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [84]:
b1 = np.array([1,2,3])
b2 = np.array([4,5,6])
print(b1)
print(b2)
print(np.stack((b1,b2),axis=0)) # row wise
print(np.stack((b1,b2),axis=1)) # colum wise

[1 2 3]
[4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]


In [85]:
print(a4)
print(a5)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [86]:
print(np.concatenate((a4,a5),axis=0)) 
print(np.concatenate((a4,a5),axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


# Spliting

In [89]:
a4 = np.arange(20).reshape(4,5)
print(a4)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [92]:
parts = np.hsplit(a4,5)
print(parts)

[array([[ 0],
       [ 5],
       [10],
       [15]]), array([[ 1],
       [ 6],
       [11],
       [16]]), array([[ 2],
       [ 7],
       [12],
       [17]]), array([[ 3],
       [ 8],
       [13],
       [18]]), array([[ 4],
       [ 9],
       [14],
       [19]])]


In [93]:
a5 = np.arange(12,24).reshape(3,4)
print(a5)

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [94]:
top,bottom = np.vsplit(a5,[2])
print(top)
print(bottom)

[[12 13 14 15]
 [16 17 18 19]]
[[20 21 22 23]]


In [96]:
a3 = np.arange(24).reshape(2,3,4)
print(a3)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [98]:
left,right = np.split(a3,2,axis=2)
print(left)
print(right)

[[[ 0  1]
  [ 4  5]
  [ 8  9]]

 [[12 13]
  [16 17]
  [20 21]]]
[[[ 2  3]
  [ 6  7]
  [10 11]]

 [[14 15]
  [18 19]
  [22 23]]]
