# Array Attribute
## a.ndim , a.shape , a.size , a.iteamsize , a.dtype

In [3]:
# !pip install numpy

In [5]:
import numpy as np

In [11]:
a1 = np.arange(10,dtype=np.int32)
a2 = np.arange(12,dtype=float).reshape(3,4)     # reshape means row and col
a3 = np.arange(8).reshape(2,2,2)

print("a1:",a1)
print("a2:",a2)
print("a3:",a3)


a1: [0 1 2 3 4 5 6 7 8 9]
a2: [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
a3: [[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [13]:
print(a1.ndim)
print(a2.ndim)  # .ndim means the number of dimensions of an array.1D,,2D,3D
print(a3.ndim)

1
2
3


In [15]:
print(a1,a1.shape) # .shape tells you the size of each dimension.
print(a2,a2.shape)
print(a3,a3.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] (3, 4)
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)


In [18]:
print(a1,a1.size)  # .size tells you the total number of values in the array or .size means array mein total number of elements.
print(a2,a2.size)
print(a3,a3.size)

[0 1 2 3 4 5 6 7 8 9] 10
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] 12
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] 8


In [19]:
print(a1,a1.dtype)     #.dtype tells you data type.
print(a2,a2.dtype)
print(a3,a3.dtype)

[0 1 2 3 4 5 6 7 8 9] int32
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]] float64
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] int64


# Changing data types.

In [6]:
prices = np.array([10.9,20.2,30.8])
print(prices)
whole = prices.astype(int)
print(whole)

[10.9 20.2 30.8]
[10 20 30]


In [8]:
back_to_float = whole.astype(np.float64) # .astype is used for changing the data type.
print(back_to_float)

[10. 20. 30.]


In [9]:
ids = np.array([101,102,103])
print(ids)
as_text = ids.astype(str)
print(as_text)

[101 102 103]
['101' '102' '103']


In [12]:
flags = np.array ([0,4,0,5,1,0])
print(flags)
as_bool = flags.astype(bool)
print(as_bool)

[0 4 0 5 1 0]
[False  True False  True  True False]
