In [2]:
!pip install numpy

In [9]:
import numpy as np

# 1) Creating 1D,2D Array

In [14]:
# a =np.array([1,2,3,]) # 1D Array
print(a)
# grid = np.array([[1,2,3],[4,5,6,]]) # 2D Array
print(grid)


[1 2 3]
[[1 2 3]
 [4 5 6]]


In [16]:
a= np.array([1,2,3,])
# print(a)
grid =np.array([[1,2,3,],[4,5,6,]])
# print(grid)
print(a,a.ndim)
print(grid,grid.ndim)

[1 2 3] 1
[[1 2 3]
 [4 5 6]] 2


In [20]:
values = np.array([1,4,9,16,25])
print(np.sqrt(values))

[1. 2. 3. 4. 5.]


In [21]:
print(np.sum(values))

55


In [23]:
a = np.array([1,2,3,4])
b = np.array([[5,6,7,8],[9,10,11,12]])
print(a)
print(b)

[1 2 3 4]
[[ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
num = np.array([1,2,3,4],dtype=float)
print(num)

[1. 2. 3. 4.]


In [31]:
seq = np.array([1,11,2]) # (Start,Stop,Step)
print(seq)
grid = np.arange(16).reshape(2,2,2,2) # start = 0 stop= 16 ,grid = 2 big boxes, each with 2 boxes, each with 2 rows, each row with 2 numbers
print(grid)

[ 1 11  2]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [38]:
print(np.ones((2,3))) #  means 2 row , 3 colums 
print(np.identity(3)) # np.indentity  make a  indentity matrix 3*3

[[1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [42]:
print(np.round(np.random.random((2,3)),2)) # Rounds every random number to  decimal places: like 2

[[0.96 0.58 0.66]
 [0.6  0.79 0.32]]


In [43]:
print(np.linspace(-10,10,5)) # np.linspace(start, stop, number_of_values)

[-10.  -5.   0.   5.  10.]


In [44]:
print(np.linspace(-10,10,5,dtype=int))

[-10  -5   0   5  10]
