# 1. Numpy (Sort)

In [1]:
import numpy as np

In [3]:
np.random.seed(1)    # .seed use for constent  
a = np.random.randint(1,100,8)
print("original a:",a)

original a: [38 13 73 10 76  6 80 65]


In [5]:
print(np.sort(a))  # .sort use for shorting

[ 6 10 13 38 65 73 76 80]


In [6]:
print(a)

[38 13 73 10 76  6 80 65]


In [8]:
print(np.sort(a)[::-1])

[80 76 73 65 38 13 10  6]


In [10]:
b = np.random.randint(1,100,12).reshape(3,4)
print(b)
print(np.sort(b,axis=0)) # row

[[17  2 77 72]
 [ 7 26 51 21]
 [19 85 12 29]]
[[ 7  2 12 21]
 [17 26 51 29]
 [19 85 77 72]]


# 2. np.append

In [11]:
a = np.array([10,20,30])
print(a)
print(np.append(a,200))

[10 20 30]
[ 10  20  30 200]


In [15]:
np.random.seed(2)
b = np.arange(8).reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [18]:
print(b.shape)
extra_col = np.random.randint(1,10,(b.shape[0],1))
print(b)
print(extra_col)
print(np.append(b,extra_col,axis=1)) # column

(4, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[9]
 [8]
 [3]
 [2]]
[[0 1 9]
 [2 3 8]
 [4 5 3]
 [6 7 2]]


In [19]:
new_row = np.array([[99,99]])
print(new_row)
print(np.append(b,new_row,axis=0))


[[99 99]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [99 99]]


## 3 np.Concatenate

In [20]:
c = np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [21]:
print(np.concatenate((c,d),axis=0)) # row

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [24]:
print(np.concatenate((c,d),axis=1)) # axis 1 column

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [26]:
e1 =np.array([1,2,3])
e2 =np.array([4,5])
print(np.concatenate((e1,e2)))

[1 2 3 4 5]


# 4 np.unique

In [32]:
arr = np.array([1,1,2,2,3,3,4,4,4,5])
print(arr)

[1 1 2 2 3 3 4 4 4 5]


In [33]:
print(np.unique(arr))

[1 2 3 4 5]


In [34]:
print(arr)

[1 1 2 2 3 3 4 4 4 5]


In [35]:
values ,count = np.unique(arr,return_counts=True)
print(values)
print(count)

[1 2 3 4 5]
[2 2 2 3 1]


In [36]:
values,idx = np.unique(arr,return_index=True)
print(values)
print(idx)

[1 2 3 4 5]
[0 2 4 6 9]


# 5. np.expand_dims

In [46]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(np.expand_dims(a,axis=0).shape)

[1 2 3 4]
(4,)
(1, 4)


In [45]:
expanded = np.expand_dims(a,axis=1)
print(expanded)

[[1]
 [2]
 [3]
 [4]]


# 6. np.where

In [47]:
np.random.seed(3)
a = np.random.randint(1,100,10)
print(a)
print(np.where(a>50))

[25  4 57 73  1 22 20 75 42 11]
(array([2, 3, 7]),)


In [48]:
print(np.where(a>50,0,a))

[25  4  0  0  1 22 20  0 42 11]


In [49]:
print(np.where(a%2==0,0,a))

[25  0 57 73  1  0  0 75  0 11]


# 7. np.argmax and np.argmin

In [51]:
np.random.seed(3)
a = np.random.randint(1,100,10)
print(a)
print(np.argmax(a))
print(np.argmin(a))

[25  4 57 73  1 22 20 75 42 11]
7
4


In [53]:
b = np.random.randint(1,100,12).reshape(3,4)
print(b)
print(np.argmax(b,axis=0)) # column

[[67  3 64 61]
 [ 2 52 91 70]
 [98 30 25 63]]
[2 1 1 1]


In [55]:
print(np.argmax(b,axis=1))

[0 2 0]


# 8. np.cumsum and np.cumprod

In [57]:
a =np.array([5,10,15,20])
print(a)

[ 5 10 15 20]


In [58]:
print(np.cumsum(a))

[ 5 15 30 50]


In [61]:
b = np.arange(1,13).reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [62]:
print(a)
print(np.cumprod(a))

[ 5 10 15 20]
[    5    50   750 15000]
