# 1. Numpy (Sort)

In [3]:
import numpy as np

In [4]:
np.random.seed(1)    # .seed use for constent  
a = np.random.randint(1,100,8)
print("original a:",a)

original a: [38 13 73 10 76  6 80 65]


In [5]:
print(np.sort(a))  # .sort use for shorting

[ 6 10 13 38 65 73 76 80]


In [6]:
print(a)

[38 13 73 10 76  6 80 65]


In [7]:
print(np.sort(a)[::-1])

[80 76 73 65 38 13 10  6]


In [8]:
b = np.random.randint(1,100,12).reshape(3,4)
print(b)
print(np.sort(b,axis=0)) # row

[[17  2 77 72]
 [ 7 26 51 21]
 [19 85 12 29]]
[[ 7  2 12 21]
 [17 26 51 29]
 [19 85 77 72]]


# 2. np.append

In [9]:
a = np.array([10,20,30])
print(a)
print(np.append(a,200))

[10 20 30]
[ 10  20  30 200]


In [10]:
np.random.seed(2)
b = np.arange(8).reshape(4,2)
print(b)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]


In [11]:
print(b.shape)
extra_col = np.random.randint(1,10,(b.shape[0],1))
print(b)
print(extra_col)
print(np.append(b,extra_col,axis=1)) # column

(4, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[9]
 [9]
 [7]
 [3]]
[[0 1 9]
 [2 3 9]
 [4 5 7]
 [6 7 3]]


In [12]:
new_row = np.array([[99,99]])
print(new_row)
print(np.append(b,new_row,axis=0))


[[99 99]]
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [99 99]]


## 3 np.Concatenate

In [13]:
c = np.arange(6).reshape(2,3)
d= np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [14]:
print(np.concatenate((c,d),axis=0)) # row

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [15]:
print(np.concatenate((c,d),axis=1)) # axis 1 column

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [16]:
e1 =np.array([1,2,3])
e2 =np.array([4,5])
print(np.concatenate((e1,e2)))

[1 2 3 4 5]


# 4 np.unique

In [17]:
arr = np.array([1,1,2,2,3,3,4,4,4,5])
print(arr)

[1 1 2 2 3 3 4 4 4 5]


In [18]:
print(np.unique(arr))

[1 2 3 4 5]


In [19]:
print(arr)

[1 1 2 2 3 3 4 4 4 5]


In [20]:
values ,count = np.unique(arr,return_counts=True)
print(values)
print(count)

[1 2 3 4 5]
[2 2 2 3 1]


In [21]:
values,idx = np.unique(arr,return_index=True)
print(values)
print(idx)

[1 2 3 4 5]
[0 2 4 6 9]


# 5. np.expand_dims

In [22]:
a = np.array([1,2,3,4])
print(a)
print(a.shape)
print(np.expand_dims(a,axis=0).shape)

[1 2 3 4]
(4,)
(1, 4)


In [23]:
expanded = np.expand_dims(a,axis=1)
print(expanded)

[[1]
 [2]
 [3]
 [4]]


# 6. np.where

In [24]:
np.random.seed(3)
a = np.random.randint(1,100,10)
print(a)
print(np.where(a>50))

[25  4 57 73  1 22 20 75 42 11]
(array([2, 3, 7]),)


In [25]:
print(np.where(a>50,0,a))

[25  4  0  0  1 22 20  0 42 11]


In [26]:
print(np.where(a%2==0,0,a))

[25  0 57 73  1  0  0 75  0 11]


# 7. np.argmax and np.argmin

In [27]:
np.random.seed(3)
a = np.random.randint(1,100,10)
print(a)
print(np.argmax(a))
print(np.argmin(a))

[25  4 57 73  1 22 20 75 42 11]
7
4


In [28]:
b = np.random.randint(1,100,12).reshape(3,4)
print(b)
print(np.argmax(b,axis=0)) # column

[[22 39 97 21]
 [45 94 40 15]
 [27 82 91 23]]
[1 1 0 2]


In [29]:
print(np.argmax(b,axis=1))

[2 1 2]


# 8. np.cumsum and np.cumprod

In [30]:
a =np.array([5,10,15,20])
print(a)

[ 5 10 15 20]


In [31]:
print(np.cumsum(a))

[ 5 15 30 50]


In [32]:
b = np.arange(1,13).reshape(3,4)
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
print(a)
print(np.cumprod(a))

[ 5 10 15 20]
[    5    50   750 15000]


 # 9 np.percentile and np.median

In [35]:
np.random.seed(3)
a= np.random.randint(1,100,10)
print(a)

[25  4 57 73  1 22 20 75 42 11]


In [38]:
print(np.percentile(a,50))

23.5


In [39]:
print(np.median(a))

23.5


In [40]:
print(np.percentile(a,[25,50,75]))

[13.25 23.5  53.25]


In [41]:
print(np.percentile(a,[0,25,50,75,100]))

[ 1.   13.25 23.5  53.25 75.  ]


# 10 np.histogram

In [42]:
np.random.seed(3)
a = np.random.randint(1,100,10)
print(a)

[25  4 57 73  1 22 20 75 42 11]


In [44]:
counts,edges = np.histogram(a,bins = [0,50,100])
print(counts)
print(edges)

[7 3]
[  0  50 100]


In [46]:
counts,edges = np.histogram(a,bins=[1,25,50,75,100])
print(counts)
print(edges)

[5 2 2 1]
[  1  25  50  75 100]


In [48]:
counts,edges = np.histogram(a,bins = 4)
print(counts)
print(edges)
print(a)

[3 3 1 3]
[ 1.  19.5 38.  56.5 75. ]
[25  4 57 73  1 22 20 75 42 11]


# 11 np.corrcoef

In [55]:
salary = np.array([20000,30000,40000,50000,60000])
experience = np.array([1,2,3,5,4,])
print(salary)
print(experience)

[20000 30000 40000 50000 60000]
[1 2 3 5 4]


In [56]:
print(np.corrcoef(salary,experience))

[[1.  0.9]
 [0.9 1. ]]


In [57]:
np.random.seed(4)
x = np.arange(10)
y = np.random.randint(1,100,10)
print(y)
print(np.round(np.corrcoef(x,y),3))

[47 56 70  2 88 73 51 10 59 95]
[[1.    0.174]
 [0.174 1.   ]]


In [58]:
print(salary)
print(experience)

[20000 30000 40000 50000 60000]
[1 2 3 5 4]


In [60]:
print(np.corrcoef(salary,salary))

[[1. 1.]
 [1. 1.]]


# 12 np.isin

In [61]:
a = np.array([15,20,35,40,55,60,75,80])
items = [20,40,60,80,100]
print(a)
print(np.isin(a,items))

[15 20 35 40 55 60 75 80]
[False  True False  True False  True False  True]


In [62]:
print(a[np.isin(a,items)])

[20 40 60 80]


In [63]:
print(a[~np.isin(a,items)])

[15 35 55 75]


In [64]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
print(np.isin(b,[0,5,10]))

[[ True False False False]
 [False  True False False]
 [False False  True False]]


# 13 np.flip

In [67]:
a = np.array([10,20,30,40,50])
print(a)
print(np.flip(a))

[10 20 30 40 50]
[50 40 30 20 10]


In [70]:
b = np.arange(12).reshape(3,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [72]:
print(np.flip(b,axis=0)) # axis 0 column

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [74]:
print(np.flip(b,axis=1)) # row

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


# 14 np.put and np.delete

In [76]:
a = np.array([10,20,30,40,50])
np.put(a,[0,1],[110,530])
print(a)

[110 530  30  40  50]


In [78]:
b = np.array([10,20,30,40,50])
print(b)
print(np.delete(b,[0,2,4]))
print(b)

[10 20 30 40 50]
[20 40]
[10 20 30 40 50]


In [79]:
c= np.arange(12).reshape(3,4)
print(c)
print(np.delete(c,1,axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 8  9 10 11]]


# 15 Set Function

In [80]:
m = np.array([1,2,3,4,5])
n =np.array([3,4,5,6,7])
print(m)
print(n)

[1 2 3 4 5]
[3 4 5 6 7]


In [82]:
print(np.union1d(m,n)) # delete the duplicate 

[1 2 3 4 5 6 7]


In [84]:
print(np.intersect1d(m,n))

[3 4 5]


In [87]:
print(np.setdiff1d(m,n))

[1 2]


In [90]:
print(np.setxor1d(m,n))

[1 2 6 7]


In [91]:
print(m)
print(n)

[1 2 3 4 5]
[3 4 5 6 7]


# 16 np.clip

In [93]:
np.random.seed(3)
a = np.random.randint(1,100,10)
print(a)

[25  4 57 73  1 22 20 75 42 11]


In [94]:
print(np.clip(a,a_min=25,a_max=75))

[25 25 57 73 25 25 25 75 42 25]


In [97]:
print(np.clip(a,a_min=50,a_max=None))

[50 50 57 73 50 50 50 75 50 50]


In [98]:
print(np.clip(a,a_min=None,a_max=50))

[25  4 50 50  1 22 20 50 42 11]
